title: Soheepedia（そひぺでぃあ）
description: RIIZE ソヒ（SOHEE）の情報まとめ
theme: minima
markdown: kramdown
url: "https://sohee-japan.github.io"
baseurl: "/soheepedia"
include:
  - sitemap.xml
plugins:
  - jekyll-sitemap
